// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Auto-generated chip-wide boot constants. These are identical for every
// core/tile/group in a given hardware build, so they are baked in at compile
// time instead of being read from the shared bootrom at runtime by every
// core. Regenerated from the cluster config whenever the config changes.
//
// Generated by util/scripts/generate_bootdata.py from this hjson's `cluster`
// and `dram` sections. DO NOT EDIT BY HAND.

#ifndef SNRT_BOOTINFO_H_
#define SNRT_BOOTINFO_H_

#define SNRT_BOOT_CORE_COUNT       ${cfg['cluster']['nr_cores']}
#define SNRT_BOOT_HARTID_BASE      ${cfg['cluster']['cluster_base_hartid']}
#define SNRT_BOOT_TCDM_START       ${hex(cfg['cluster']['cluster_base_addr'])}
#define SNRT_BOOT_TCDM_SIZE        ${hex(cfg['cluster']['tcdm']['size'] * 1024)}
#define SNRT_BOOT_TCDM_OFFSET      ${hex(cfg['cluster']['cluster_base_offset'])}
#define SNRT_BOOT_GLOBAL_MEM_START ${hex(cfg['dram']['address'])}
#define SNRT_BOOT_GLOBAL_MEM_END   ${hex(cfg['dram']['address'] + cfg['dram']['length'])}
#define SNRT_BOOT_TILE_COUNT       ${cfg['cluster']['nr_tiles']}

#endif // SNRT_BOOTINFO_H_
