// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module cachepool_peripheral_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 7
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output cachepool_peripheral_reg_pkg::cachepool_peripheral_reg2hw_t reg2hw, // Write
  input  cachepool_peripheral_reg_pkg::cachepool_peripheral_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import cachepool_peripheral_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [9:0] hart_select_0_qs;
  logic [9:0] hart_select_0_wd;
  logic hart_select_0_we;
  logic [9:0] hart_select_1_qs;
  logic [9:0] hart_select_1_wd;
  logic hart_select_1_we;
  logic [31:0] cl_clint_set_wd;
  logic cl_clint_set_we;
  logic [31:0] cl_clint_clear_wd;
  logic cl_clint_clear_we;
  logic [31:0] hw_barrier_qs;
  logic hw_barrier_re;
  logic icache_prefetch_enable_wd;
  logic icache_prefetch_enable_we;
  logic spatz_status_wd;
  logic spatz_status_we;
  logic [31:0] spatz_cycle_qs;
  logic [31:0] spatz_cycle_wd;
  logic spatz_cycle_we;
  logic [31:0] cluster_boot_control_qs;
  logic [31:0] cluster_boot_control_wd;
  logic cluster_boot_control_we;
  logic cluster_eoc_exit_qs;
  logic cluster_eoc_exit_wd;
  logic cluster_eoc_exit_we;
  logic [9:0] cfg_l1d_spm_qs;
  logic [9:0] cfg_l1d_spm_wd;
  logic cfg_l1d_spm_we;
  logic [1:0] cfg_l1d_insn_qs;
  logic [1:0] cfg_l1d_insn_wd;
  logic cfg_l1d_insn_we;
  logic l1d_spm_commit_qs;
  logic l1d_spm_commit_wd;
  logic l1d_spm_commit_we;
  logic l1d_insn_commit_qs;
  logic l1d_insn_commit_wd;
  logic l1d_insn_commit_we;
  logic l1d_flush_status_qs;
  logic l1d_flush_status_re;
  logic [3:0] l1d_private_qs;
  logic [3:0] l1d_private_wd;
  logic l1d_private_we;
  logic [4:0] xbar_offset_qs;
  logic [4:0] xbar_offset_wd;
  logic xbar_offset_we;
  logic xbar_offset_commit_qs;
  logic xbar_offset_commit_wd;
  logic xbar_offset_commit_we;

  // Register instances

  // Subregister 0 of Multireg hart_select
  // R[hart_select_0]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RW"),
    .RESVAL  (10'h0)
  ) u_hart_select_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hart_select_0_we),
    .wd     (hart_select_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hart_select[0].q ),

    // to register interface (read)
    .qs     (hart_select_0_qs)
  );

  // Subregister 1 of Multireg hart_select
  // R[hart_select_1]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RW"),
    .RESVAL  (10'h0)
  ) u_hart_select_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hart_select_1_we),
    .wd     (hart_select_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hart_select[1].q ),

    // to register interface (read)
    .qs     (hart_select_1_qs)
  );


  // R[cl_clint_set]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_cl_clint_set (
    .re     (1'b0),
    .we     (cl_clint_set_we),
    .wd     (cl_clint_set_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.cl_clint_set.qe),
    .q      (reg2hw.cl_clint_set.q ),
    .qs     ()
  );


  // R[cl_clint_clear]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_cl_clint_clear (
    .re     (1'b0),
    .we     (cl_clint_clear_we),
    .wd     (cl_clint_clear_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.cl_clint_clear.qe),
    .q      (reg2hw.cl_clint_clear.q ),
    .qs     ()
  );


  // R[hw_barrier]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_hw_barrier (
    .re     (hw_barrier_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.hw_barrier.d),
    .qre    (),
    .qe     (),
    .q      (reg2hw.hw_barrier.q ),
    .qs     (hw_barrier_qs)
  );


  // R[icache_prefetch_enable]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h1)
  ) u_icache_prefetch_enable (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (icache_prefetch_enable_we),
    .wd     (icache_prefetch_enable_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.icache_prefetch_enable.q ),

    .qs     ()
  );


  // R[spatz_status]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("WO"),
    .RESVAL  (1'h0)
  ) u_spatz_status (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (spatz_status_we),
    .wd     (spatz_status_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.spatz_status.q ),

    .qs     ()
  );


  // R[spatz_cycle]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_spatz_cycle (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (spatz_cycle_we),
    .wd     (spatz_cycle_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.spatz_cycle.q ),

    // to register interface (read)
    .qs     (spatz_cycle_qs)
  );


  // R[cluster_boot_control]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_cluster_boot_control (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cluster_boot_control_we),
    .wd     (cluster_boot_control_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cluster_boot_control.q ),

    // to register interface (read)
    .qs     (cluster_boot_control_qs)
  );


  // R[cluster_eoc_exit]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_cluster_eoc_exit (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cluster_eoc_exit_we),
    .wd     (cluster_eoc_exit_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cluster_eoc_exit.q ),

    // to register interface (read)
    .qs     (cluster_eoc_exit_qs)
  );


  // R[cfg_l1d_spm]: V(False)

  prim_subreg #(
    .DW      (10),
    .SWACCESS("RW"),
    .RESVAL  (10'h20)
  ) u_cfg_l1d_spm (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_l1d_spm_we),
    .wd     (cfg_l1d_spm_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_l1d_spm.q ),

    // to register interface (read)
    .qs     (cfg_l1d_spm_qs)
  );


  // R[cfg_l1d_insn]: V(False)

  prim_subreg #(
    .DW      (2),
    .SWACCESS("RW"),
    .RESVAL  (2'h0)
  ) u_cfg_l1d_insn (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_l1d_insn_we),
    .wd     (cfg_l1d_insn_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_l1d_insn.q ),

    // to register interface (read)
    .qs     (cfg_l1d_insn_qs)
  );


  // R[l1d_spm_commit]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h1)
  ) u_l1d_spm_commit (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (l1d_spm_commit_we),
    .wd     (l1d_spm_commit_wd),

    // from internal hardware
    .de     (hw2reg.l1d_spm_commit.de),
    .d      (hw2reg.l1d_spm_commit.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.l1d_spm_commit.q ),

    // to register interface (read)
    .qs     (l1d_spm_commit_qs)
  );


  // R[l1d_insn_commit]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_l1d_insn_commit (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (l1d_insn_commit_we),
    .wd     (l1d_insn_commit_wd),

    // from internal hardware
    .de     (hw2reg.l1d_insn_commit.de),
    .d      (hw2reg.l1d_insn_commit.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.l1d_insn_commit.q ),

    // to register interface (read)
    .qs     (l1d_insn_commit_qs)
  );


  // R[l1d_flush_status]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_l1d_flush_status (
    .re     (l1d_flush_status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.l1d_flush_status.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (l1d_flush_status_qs)
  );


  // R[l1d_private]: V(False)

  prim_subreg #(
    .DW      (4),
    .SWACCESS("RW"),
    .RESVAL  (4'h0)
  ) u_l1d_private (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (l1d_private_we),
    .wd     (l1d_private_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.l1d_private.q ),

    // to register interface (read)
    .qs     (l1d_private_qs)
  );


  // R[xbar_offset]: V(False)

  prim_subreg #(
    .DW      (5),
    .SWACCESS("RW"),
    .RESVAL  (5'h0)
  ) u_xbar_offset (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (xbar_offset_we),
    .wd     (xbar_offset_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.xbar_offset.q ),

    // to register interface (read)
    .qs     (xbar_offset_qs)
  );


  // R[xbar_offset_commit]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_xbar_offset_commit (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (xbar_offset_commit_we),
    .wd     (xbar_offset_commit_wd),

    // from internal hardware
    .de     (hw2reg.xbar_offset_commit.de),
    .d      (hw2reg.xbar_offset_commit.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.xbar_offset_commit.q ),

    // to register interface (read)
    .qs     (xbar_offset_commit_qs)
  );




  logic [17:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == CACHEPOOL_PERIPHERAL_HART_SELECT_0_OFFSET);
    addr_hit[ 1] = (reg_addr == CACHEPOOL_PERIPHERAL_HART_SELECT_1_OFFSET);
    addr_hit[ 2] = (reg_addr == CACHEPOOL_PERIPHERAL_CL_CLINT_SET_OFFSET);
    addr_hit[ 3] = (reg_addr == CACHEPOOL_PERIPHERAL_CL_CLINT_CLEAR_OFFSET);
    addr_hit[ 4] = (reg_addr == CACHEPOOL_PERIPHERAL_HW_BARRIER_OFFSET);
    addr_hit[ 5] = (reg_addr == CACHEPOOL_PERIPHERAL_ICACHE_PREFETCH_ENABLE_OFFSET);
    addr_hit[ 6] = (reg_addr == CACHEPOOL_PERIPHERAL_SPATZ_STATUS_OFFSET);
    addr_hit[ 7] = (reg_addr == CACHEPOOL_PERIPHERAL_SPATZ_CYCLE_OFFSET);
    addr_hit[ 8] = (reg_addr == CACHEPOOL_PERIPHERAL_CLUSTER_BOOT_CONTROL_OFFSET);
    addr_hit[ 9] = (reg_addr == CACHEPOOL_PERIPHERAL_CLUSTER_EOC_EXIT_OFFSET);
    addr_hit[10] = (reg_addr == CACHEPOOL_PERIPHERAL_CFG_L1D_SPM_OFFSET);
    addr_hit[11] = (reg_addr == CACHEPOOL_PERIPHERAL_CFG_L1D_INSN_OFFSET);
    addr_hit[12] = (reg_addr == CACHEPOOL_PERIPHERAL_L1D_SPM_COMMIT_OFFSET);
    addr_hit[13] = (reg_addr == CACHEPOOL_PERIPHERAL_L1D_INSN_COMMIT_OFFSET);
    addr_hit[14] = (reg_addr == CACHEPOOL_PERIPHERAL_L1D_FLUSH_STATUS_OFFSET);
    addr_hit[15] = (reg_addr == CACHEPOOL_PERIPHERAL_L1D_PRIVATE_OFFSET);
    addr_hit[16] = (reg_addr == CACHEPOOL_PERIPHERAL_XBAR_OFFSET_OFFSET);
    addr_hit[17] = (reg_addr == CACHEPOOL_PERIPHERAL_XBAR_OFFSET_COMMIT_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(CACHEPOOL_PERIPHERAL_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(CACHEPOOL_PERIPHERAL_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(CACHEPOOL_PERIPHERAL_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(CACHEPOOL_PERIPHERAL_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(CACHEPOOL_PERIPHERAL_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(CACHEPOOL_PERIPHERAL_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(CACHEPOOL_PERIPHERAL_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(CACHEPOOL_PERIPHERAL_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(CACHEPOOL_PERIPHERAL_PERMIT[17] & ~reg_be)))));
  end

  assign hart_select_0_we = addr_hit[0] & reg_we & !reg_error;
  assign hart_select_0_wd = reg_wdata[9:0];

  assign hart_select_1_we = addr_hit[1] & reg_we & !reg_error;
  assign hart_select_1_wd = reg_wdata[9:0];

  assign cl_clint_set_we = addr_hit[2] & reg_we & !reg_error;
  assign cl_clint_set_wd = reg_wdata[31:0];

  assign cl_clint_clear_we = addr_hit[3] & reg_we & !reg_error;
  assign cl_clint_clear_wd = reg_wdata[31:0];

  assign hw_barrier_re = addr_hit[4] & reg_re & !reg_error;

  assign icache_prefetch_enable_we = addr_hit[5] & reg_we & !reg_error;
  assign icache_prefetch_enable_wd = reg_wdata[0];

  assign spatz_status_we = addr_hit[6] & reg_we & !reg_error;
  assign spatz_status_wd = reg_wdata[0];

  assign spatz_cycle_we = addr_hit[7] & reg_we & !reg_error;
  assign spatz_cycle_wd = reg_wdata[31:0];

  assign cluster_boot_control_we = addr_hit[8] & reg_we & !reg_error;
  assign cluster_boot_control_wd = reg_wdata[31:0];

  assign cluster_eoc_exit_we = addr_hit[9] & reg_we & !reg_error;
  assign cluster_eoc_exit_wd = reg_wdata[0];

  assign cfg_l1d_spm_we = addr_hit[10] & reg_we & !reg_error;
  assign cfg_l1d_spm_wd = reg_wdata[9:0];

  assign cfg_l1d_insn_we = addr_hit[11] & reg_we & !reg_error;
  assign cfg_l1d_insn_wd = reg_wdata[1:0];

  assign l1d_spm_commit_we = addr_hit[12] & reg_we & !reg_error;
  assign l1d_spm_commit_wd = reg_wdata[0];

  assign l1d_insn_commit_we = addr_hit[13] & reg_we & !reg_error;
  assign l1d_insn_commit_wd = reg_wdata[0];

  assign l1d_flush_status_re = addr_hit[14] & reg_re & !reg_error;

  assign l1d_private_we = addr_hit[15] & reg_we & !reg_error;
  assign l1d_private_wd = reg_wdata[3:0];

  assign xbar_offset_we = addr_hit[16] & reg_we & !reg_error;
  assign xbar_offset_wd = reg_wdata[4:0];

  assign xbar_offset_commit_we = addr_hit[17] & reg_we & !reg_error;
  assign xbar_offset_commit_wd = reg_wdata[0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[9:0] = hart_select_0_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[9:0] = hart_select_1_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = hw_barrier_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = '0;
      end

      addr_hit[6]: begin
        reg_rdata_next[0] = '0;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = spatz_cycle_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = cluster_boot_control_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[0] = cluster_eoc_exit_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[9:0] = cfg_l1d_spm_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[1:0] = cfg_l1d_insn_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[0] = l1d_spm_commit_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[0] = l1d_insn_commit_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[0] = l1d_flush_status_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[3:0] = l1d_private_qs;
      end

      addr_hit[16]: begin
        reg_rdata_next[4:0] = xbar_offset_qs;
      end

      addr_hit[17]: begin
        reg_rdata_next[0] = xbar_offset_commit_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module cachepool_peripheral_reg_top_intf
#(
  parameter int AW = 7,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output cachepool_peripheral_reg_pkg::cachepool_peripheral_reg2hw_t reg2hw, // Write
  input  cachepool_peripheral_reg_pkg::cachepool_peripheral_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  cachepool_peripheral_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


